### ISSUE TITLE
Minetweaker Recipe issue

### ISSUE THREAD

**Issue by volcano010** [Danymaddox/InitiumArcanus2#41]
Hi, this is intentional?

https://imgur.com/XAkAxIu

**Comment by Danymaddox** [comment]
Hi! I just tested on a new profile but I cannot reproduce this error. Did you remove/add any mod? How did you install my modpack?

**Comment by volcano010** [comment]
I just remove these mods, because I don't usually play them in any modpack

https://imgur.com/5Wx64n0

**Comment by Danymaddox** [comment]
So you still have Lapis Stays in the Enchanting Table mod?

**Comment by volcano010** [comment]
I forgot to test with that mod yesterday. Now it works correctly.

PS: Is there any chance that you will add some creative items in your future updates? because I usually play modpack with these items, like enigmatica and ftb infinity evolved, which tend to be more like a final challenge. Sorry if my english is bad

**Comment by Danymaddox** [comment]
Cool, I'm glad to see it working :)

I do not pretend to add any creative items in future updates, since the only one that comes to my mind is Thaumcraft's creative Flux Sponge, whic removes all Flux in a 3x3 chunk area, and will destroy part of the experience. 

Do not worry about your english, is perfect :) (And I'm not a native Englis speeker either :P)
